export const ADD_DATA_REQUEST = "ADD_DATA_REQUEST";
export const ADD_DATA_SUCCESS = "ADD_DATA_SUCCESS";
export const ADD_DATA_FAIL = "ADD_DATA_FAIL";

export const GET_DATA_REQUEST = "GET_DATA_REQUEST";
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
export const GET_DATA_FAIL = "GET_DATA_FAIL";


export const DELETE_DATA_REQUEST = "DELETE_DATA_REQUEST"
export const DELETE_DATA_SUCCESS = "DELETE_DATA_SUCCESS"
export const DELETE_DATA_FAIL = "DELETE_DATA_FAIL"

export const EDIT_DATA_REQUEST = "EDIT_DATA_REQUEST"
export const EDIT_DATA_SUCCESS = "EDIT_DATA_SUCCESS"
export const EDIT_DATA_FAIL = "EDIT_DATA_FAIL"

